# Generated by Django 6.0.1 on 2026-01-22 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.categorie', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code entrepôt')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'entrepôt")),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Entrepôt',
                'verbose_name_plural': 'Entrepôts',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code produit')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('unite', models.CharField(default='PCE', max_length=20, verbose_name='Unité de mesure')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Prix d'achat")),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de vente')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de TVA (%)')),
                ('stock_min', models.IntegerField(default=0, verbose_name='Stock minimum')),
                ('stock_max', models.IntegerField(default=0, verbose_name='Stock maximum')),
                ('seuil_reapprovisionnement', models.IntegerField(default=0, verbose_name='Seuil de réapprovisionnement')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('AJUSTEMENT', 'Ajustement'), ('TRANSFERT', 'Transfert')], max_length=20, verbose_name='Type de mouvement')),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('reference', models.CharField(max_length=50, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.entrepot', verbose_name='Entrepôt')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date'],
            },
        ),
    ]
