# Generated by Django 6.0.1 on 2026-01-30 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0, verbose_name='Quantité en stock')),
                ('date_derniere_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.entrepot', verbose_name='Entrepôt')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'unique_together': {('produit', 'entrepot')},
            },
        ),
    ]
