# Generated by Django 6.0.1 on 2026-01-22 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(max_length=50, unique=True, verbose_name='Numéro de commande')),
                ('date_commande', models.DateField(auto_now_add=True, verbose_name='Date de commande')),
                ('date_livraison_prevue', models.DateField(verbose_name='Date de livraison prévue')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYEE', 'Envoyée'), ('CONFIRMEE', 'Confirmée'), ('RECUE', 'Reçue'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sous-total')),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant TVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.entrepot', verbose_name='Entrepôt')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': "Commande d'achat",
                'verbose_name_plural': "Commandes d'achat",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('quantite_recue', models.IntegerField(default=0, verbose_name='Quantité reçue')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achats.commandeachat', verbose_name='Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': "Ligne de commande d'achat",
                'verbose_name_plural': "Lignes de commande d'achat",
            },
        ),
    ]
