# Generated by Django 6.0.1 on 2026-01-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeachat',
            name='numero_commande',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Numéro de commande'),
        ),
        migrations.AlterField(
            model_name='commandeachat',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('CONFIRMEE', 'Confirmée'), ('ENVOYEE', 'Envoyée'), ('RECUE', 'Reçue'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20, verbose_name='Statut'),
        ),
    ]
