# Generated by Django 6.0.1 on 2026-01-30 12:58

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_alter_commandeachat_numero_commande_and_more'),
        ('base', '0001_initial'),
        ('comptabilite', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_paiement', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Numéro de paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant payé')),
                ('date_paiement', models.DateField(verbose_name='Date de paiement')),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('CARTE', 'Carte bancaire'), ('MOBILE', 'Paiement mobile')], default='VIREMENT', max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence (n° chèque, virement, etc.)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Paiement fournisseur',
                'verbose_name_plural': 'Paiements fournisseurs',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.AlterModelOptions(
            name='commandeachat',
            options={'ordering': ['-date_creation'], 'permissions': [('can_validate_commande_achat', "Peut valider les commandes d'achat"), ('can_cancel_commande_achat', "Peut annuler les commandes d'achat")], 'verbose_name': "Commande d'achat", 'verbose_name_plural': "Commandes d'achat"},
        ),
        migrations.AlterModelOptions(
            name='lignecommandeachat',
            options={'ordering': ['id'], 'verbose_name': "Ligne de commande d'achat", 'verbose_name_plural': "Lignes de commande d'achat"},
        ),
        migrations.AddField(
            model_name='commandeachat',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AddField(
            model_name='commandeachat',
            name='date_reception',
            field=models.DateField(blank=True, null=True, verbose_name='Date de réception'),
        ),
        migrations.AddField(
            model_name='commandeachat',
            name='piece_comptable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_achat', to='comptabilite.piece', verbose_name='Pièce comptable'),
        ),
        migrations.AddField(
            model_name='commandeachat',
            name='raison_annulation',
            field=models.TextField(blank=True, verbose_name="Raison de l'annulation"),
        ),
        migrations.AddField(
            model_name='lignecommandeachat',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 30, 12, 58, 25, 298542, tzinfo=datetime.timezone.utc), verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lignecommandeachat',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='commandeachat',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_achat_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='commandeachat',
            name='date_livraison_prevue',
            field=models.DateField(blank=True, null=True, verbose_name='Date de livraison prévue'),
        ),
        migrations.AlterField(
            model_name='commandeachat',
            name='entrepot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_achat', to='stock.entrepot', verbose_name='Entrepôt de destination'),
        ),
        migrations.AlterField(
            model_name='commandeachat',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_achat', to='base.fournisseur', verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='commandeachat',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant TVA'),
        ),
        migrations.AlterField(
            model_name='commandeachat',
            name='sous_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sous-total HT'),
        ),
        migrations.AlterField(
            model_name='commandeachat',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('CONFIRMEE', 'Confirmée'), ('ENVOYEE', 'Envoyée'), ('RECUE', 'Reçue'), ('FACTUREE', 'Facturée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='commandeachat',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total TTC'),
        ),
        migrations.AlterField(
            model_name='lignecommandeachat',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix unitaire HT'),
        ),
        migrations.AlterField(
            model_name='lignecommandeachat',
            name='quantite',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité commandée'),
        ),
        migrations.AlterField(
            model_name='lignecommandeachat',
            name='quantite_recue',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité reçue'),
        ),
        migrations.AlterField(
            model_name='lignecommandeachat',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taux TVA (%)'),
        ),
        migrations.AlterUniqueTogether(
            name='lignecommandeachat',
            unique_together={('commande', 'produit')},
        ),
        migrations.AddIndex(
            model_name='commandeachat',
            index=models.Index(fields=['numero_commande'], name='achats_comm_numero__8ff586_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeachat',
            index=models.Index(fields=['statut'], name='achats_comm_statut_cce4a3_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeachat',
            index=models.Index(fields=['date_commande'], name='achats_comm_date_co_e85d01_idx'),
        ),
        migrations.AddIndex(
            model_name='commandeachat',
            index=models.Index(fields=['fournisseur'], name='achats_comm_fournis_7de56a_idx'),
        ),
        migrations.AddField(
            model_name='paiementfournisseur',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='achats.commandeachat', verbose_name="Commande d'achat"),
        ),
        migrations.AddField(
            model_name='paiementfournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_recus', to='base.fournisseur', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='paiementfournisseur',
            name='piece_comptable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_fournisseur', to='comptabilite.piece', verbose_name='Pièce comptable'),
        ),
        migrations.AddField(
            model_name='paiementfournisseur',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par'),
        ),
    ]
