# Generated by Django 6.0.1 on 2026-01-31 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire')),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise (%)')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.facture', verbose_name='Facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
            },
        ),
    ]
