# Generated by Django 6.0.1 on 2026-02-07 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('module', models.CharField(choices=[('CLIENTS', 'Clients'), ('FOURNISSEURS', 'Fournisseurs'), ('STOCK', 'Stock'), ('VENTES', 'Ventes'), ('ACHATS', 'Achats'), ('COMPTABILITE', 'Comptabilité'), ('RAPPORTS', 'Rapports'), ('ADMINISTRATION', 'Administration')], max_length=50, verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['module', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='LogConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_connexion', models.DateTimeField(auto_now_add=True, verbose_name='Date de connexion')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('succes', models.BooleanField(default=True, verbose_name='Succès')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_connexion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de connexion',
                'verbose_name_plural': 'Logs de connexion',
                'ordering': ['-date_connexion'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Token')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_expiration', models.DateTimeField(verbose_name="Date d'expiration")),
                ('utilise', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de réinitialisation',
                'verbose_name_plural': 'Tokens de réinitialisation',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('MANAGER', 'Gestionnaire'), ('COMPTABLE', 'Comptable'), ('COMMERCIAL', 'Commercial'), ('MAGASINIER', 'Magasinier'), ('USER', 'Utilisateur')], default='USER', max_length=20, verbose_name='Rôle')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profils/', verbose_name='Photo de profil')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA activé')),
                ('two_factor_secret', models.CharField(blank=True, max_length=32, verbose_name='Secret 2FA')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('email_verification_token', models.CharField(blank=True, max_length=100, verbose_name='Token de vérification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('dernier_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernier login')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('MANAGER', 'Gestionnaire'), ('COMPTABLE', 'Comptable'), ('COMMERCIAL', 'Commercial'), ('MAGASINIER', 'Magasinier'), ('USER', 'Utilisateur')], max_length=20, verbose_name='Rôle')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.permission')),
            ],
            options={
                'verbose_name': 'Rôle-Permission',
                'verbose_name_plural': 'Rôles-Permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
