# Generated by Django 6.0.1 on 2026-01-22 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la banque')),
                ('numero_compte', models.CharField(max_length=50, verbose_name='Numéro de compte')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('swift', models.CharField(blank=True, max_length=11, verbose_name='Code SWIFT/BIC')),
                ('devise', models.CharField(default='XOF', max_length=3, verbose_name='Devise')),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Solde initial')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
            ],
            options={
                'verbose_name': 'Banque',
                'verbose_name_plural': 'Banques',
            },
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'exercice")),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('est_cloture', models.BooleanField(default=False, verbose_name='Est clôturé')),
                ('date_cloture', models.DateField(blank=True, null=True, verbose_name='Date de clôture')),
            ],
            options={
                'verbose_name': 'Exercice comptable',
                'verbose_name_plural': 'Exercices comptables',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code du journal')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('type_journal', models.CharField(choices=[('VENTE', 'Ventes'), ('ACHAT', 'Achats'), ('BANQUE', 'Banque'), ('CAISSE', 'Caisse'), ('OD', 'Opérations diverses')], max_length=20, verbose_name='Type de journal')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_piece', models.CharField(max_length=50, unique=True, verbose_name='Numéro de pièce')),
                ('date_piece', models.DateField(verbose_name='Date de la pièce')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('est_validee', models.BooleanField(default=False, verbose_name='Est validée')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptabilite.exercice', verbose_name='Exercice')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptabilite.journal', verbose_name='Journal')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
            ],
            options={
                'verbose_name': 'Pièce comptable',
                'verbose_name_plural': 'Pièces comptables',
                'ordering': ['-date_piece'],
            },
        ),
        migrations.CreateModel(
            name='MouvementBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mouvement', models.DateField(verbose_name='Date du mouvement')),
                ('type_mouvement', models.CharField(choices=[('CREDIT', 'Crédit (Entrée)'), ('DEBIT', 'Débit (Sortie)')], max_length=10, verbose_name='Type de mouvement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('est_rapproche', models.BooleanField(default=False, verbose_name='Est rapproché')),
                ('date_rapprochement', models.DateField(blank=True, null=True, verbose_name='Date de rapprochement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.banque', verbose_name='Banque')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.piece', verbose_name='Pièce comptable')),
            ],
            options={
                'verbose_name': 'Mouvement bancaire',
                'verbose_name_plural': 'Mouvements bancaires',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='PlanComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(max_length=20, unique=True, verbose_name='Numéro de compte')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('type_compte', models.CharField(choices=[('ACTIF', 'Actif'), ('PASSIF', 'Passif'), ('CHARGE', 'Charge'), ('PRODUIT', 'Produit')], max_length=20, verbose_name='Type de compte')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('compte_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comptabilite.plancomptable', verbose_name='Compte parent')),
            ],
            options={
                'verbose_name': 'Plan comptable',
                'verbose_name_plural': 'Plan comptable',
                'ordering': ['numero_compte'],
            },
        ),
        migrations.CreateModel(
            name='Ecriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Débit')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Crédit')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.client', verbose_name='Client')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.fournisseur', verbose_name='Fournisseur')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='comptabilite.piece', verbose_name='Pièce')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptabilite.plancomptable', verbose_name='Compte')),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
            },
        ),
        migrations.AddField(
            model_name='banque',
            name='compte_comptable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptabilite.plancomptable', verbose_name='Compte comptable associé'),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_prevu', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant prévu')),
                ('mois', models.IntegerField(verbose_name='Mois (1-12)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.exercice', verbose_name='Exercice')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.plancomptable', verbose_name='Compte')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'unique_together': {('exercice', 'compte', 'mois')},
            },
        ),
    ]
