# Generated by Django 6.0.1 on 2026-01-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code client')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(max_length=100, verbose_name='Pays')),
                ('numero_fiscal', models.CharField(blank=True, max_length=50, verbose_name='Numéro fiscal')),
                ('limite_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Limite de crédit')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('numero_fiscal', models.CharField(max_length=50, verbose_name='Numéro fiscal (NINEA)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entreprise/', verbose_name='Logo')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code fournisseur')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du fournisseur')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(max_length=100, verbose_name='Pays')),
                ('numero_fiscal', models.CharField(blank=True, max_length=50, verbose_name='Numéro fiscal')),
                ('delai_paiement', models.IntegerField(default=30, verbose_name='Délai de paiement (jours)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
    ]
